/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.viirya.gclient;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int ItemImage=0x7f040000;
        public static final int LinearLayout01=0x7f040003;
        public static final int LinearLayout02=0x7f040001;
        public static final int MyListView=0x7f040004;
        public static final int clusterview=0x7f040002;
        public static final int query=0x7f040005;
        public static final int search=0x7f040006;
    }
    public static final class layout {
        public static final int cluster=0x7f020000;
        public static final int cluster_content=0x7f020001;
        public static final int cluster_list=0x7f020002;
        public static final int main=0x7f020003;
    }
    public static final class string {
        public static final int app_name=0x7f030000;
        public static final int cluster_label=0x7f030001;
        public static final int onsearch=0x7f030002;
    }
}
